server.port=8081
spring.application.name=producto-cliente

# Configuración de Eureka
eureka.client.service-url.defaultZone=http://localhost:8000/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Microservicio1
producto.service.url=http://localhost:8085
producto.service.username=nest
producto.service.password=passnest
